---
- name: "obtain provided crypto-policies "
  shell: "update-crypto-policies --show"
  register: provided_crypto_policies

- name: print provided crypto-policies
  debug: var=provided_crypto_policies