---
# tasks file for roles/global_redhat_security_features
#-------------------------------------------
- debug: msg="++++++++++++++++++++++++ TASK - The BEGIN of role global_redhat_security_features message ++++++++++++++++++++++++"
- include: begin_msg.yml
  when: ansible_distribution == "RedHat"
#-------------------------------------------
- debug: msg="++++++++++++++++++++++++ TASK - update OS | RedHat ALL versions UPDATE ++++++++++++++++++++++++"
- include: redhat_update.yml
  when: ansible_distribution == "RedHat"
#-------------------------------------------
- debug: msg="++++++++++++++++++++++++ TASK - REDHAT 6 ++++++++++++++++++++++++"
- include: redhat6_setup.yml
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == '6'
#-------------------------------------------
- debug: msg="++++++++++++++++++++++++ TASK - REDHAT 7 ++++++++++++++++++++++++"
- include: redhat7_setup.yml
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == '7'
#-------------------------------------------
- debug: msg="++++++++++++++++++++++++ TASK - REDHAT 8 ++++++++++++++++++++++++"
- include: redhat8_setup.yml
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == '8'
#-------------------------------------------
- debug: msg="++++++++++++++++++++++++ TASK - Generate report ++++++++++++++++++++++++"
- include: report.yml
  when: ansible_distribution == "RedHat"
#-------------------------------------------
- debug: msg="++++++++++++++++++++++++ TASK - The END of role global_redhat_security_features message ++++++++++++++++++++++++"
- include: end_msg.yml
...