---
# tasks file for roles/global_redhat_security_features
# display the STATUS of var_check_mode
- debug:
    msg: 
    - "### STATUS ### --- var_check_mode --- ### STATUS ###"
    - "STATUS = {{ var_check_mode }}"
    - "------------------------------------------"
    - "if TRUE = CHECK ONLY !"
    - "D A N G E R -> if FALSE = APPLY CONFIGURATION -> D A N G E R"
    - "change the value into the file: roles/global_redhat_security_features/defaults/main.yml"
    - "##########################################"
#-------------------------------------------
- name: Display OS version
  shell: cat /etc/centos-release
  register: result_os_version
- name: print OS version
  debug: var=result_os_version.stdout
 #-------------------------------------------
- debug: msg="++++++++++++++++++++++++ TASK - RedHat 8 update/upgrade ="++++++++++++++++++++++++
- name: TASK - RedHat 8 update/upgrade
  import_tasks: redhatupdate.yml
  check_mode: "{{ var_check_mode }}"
  tags:
    - redhat_update
    - RedHat8
    - global_redhat_security_features
  ignore_errors: yes
 #-------------------------------------------
- debug: msg="++++++++++++++++++++++++ TASK - install / configure fapolicyd | CONFIGURING APPLICATION WHITELISTS ="++++++++++++++++++++++++
- name: TASK - install / configure fapolicyd | CONFIGURING APPLICATION WHITELISTS
  import_tasks: fapolicyd.yml
  check_mode: "{{ var_check_mode }}"
  tags:
    - config_fapolicyd
    - RedHat8
    - global_redhat_security_features
#-------------------------------------------
- debug: msg="++++++++++++++++++++++++ TASK - install / configure crypto-policies | SYSTEM-WIDE CRYPTOGRAPHIC POLICIES ="++++++++++++++++++++++++
- name: TASK - install / configure crypto-policies | SYSTEM-WIDE CRYPTOGRAPHIC POLICIES
  import_tasks: crypto-policies.yml
  check_mode: "{{ var_check_mode }}"
  tags:
    - config_crypto-policies
    - RedHat8
    - global_redhat_security_features
#-------------------------------------------
- debug: msg="++++++++++++++++++++++++ TASK - install / configure session-recording | COCKPIT SESSION RECORDING ="++++++++++++++++++++++++
- name: TASK - install / configure session-recording | COCKPIT SESSION RECORDING
  import_tasks: session-recording.yml
  check_mode: "{{ var_check_mode }}"
  tags:
    - config_session-recording
    - RedHat8
    - global_redhat_security_features
#-------------------------------------------
- name: Generate report 
  template: 
    src: report_global_redhat_security_features.j2 
    dest: report_global_redhat_security_features.out
    owner: ransible
    group: ransible
    mode: 0640
#-------------------------------------------
- name: download report
  fetch:
    src: report_global_redhat_security_features.out
    dest: ../report_global_redhat_security_features/{{ inventory_hostname }}.out
    flat: yes
#-------------------------------------------
...