---
- name: "obtain provided crypto-policies "
  shell: "update-crypto-policies --show"
  register: provided_crypto_policies

- name: print provided crypto-policies
  debug:
    msg:
      - "The provided crypto-policies is = "
      - "{{ provided_crypto_policies.stdout }}"