---
- name: obtain OS version
  shell: cat /etc/centos-release
  register: result_os_version
- name: register variable for report / "O/S version before the upgrade TASK"
  debug: var=result_os_version.stdout

- name: update the system
  yum:
    name: "*"
    state: latest

- name: restart system to reboot to newest kernel
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0

- name: wait for 10 seconds
  pause:
    seconds: 10

- name: wait for the system to reboot
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 60