---
  # File redhat8_setup.yml for the task that config ONLY CentOs "8" servers
    
#-------------------------------------------
- debug: msg="++++++++++++++++++++++++ TASK - install / configure fapolicyd | CONFIGURING APPLICATION WHITELISTS ="++++++++++++++++++++++++
- name: TASK - install / configure fapolicyd | CONFIGURING APPLICATION WHITELISTS
  import_tasks: redhat8_fapolicyd.yml
  tags:
    - config_redhat8_fapolicyd
    - RedHat8
    - global_redhat_security_features

- name: get service facts
  service_facts:
- name: "@@@ Verify the service fapolicyd status @@@"
  debug:
    var: ansible_facts.services["fapolicyd.service"]
#-------------------------------------------
- debug: msg="++++++++++++++++++++++++ TASK - install / configure crypto-policies | SYSTEM-WIDE CRYPTOGRAPHIC POLICIES "++++++++++++++++++++++++
- name: TASK - install / configure crypto-policies | SYSTEM-WIDE CRYPTOGRAPHIC POLICIES
  import_tasks: redhat8_crypto-policies.yml
  tags:
    - config_redhat8_crypto_policies
    - RedHat8
    - global_redhat_security_features
#-------------------------------------------
- debug: msg="++++++++++++++++++++++++ TASK - install / configure session-recording | COCKPIT SESSION RECORDING "++++++++++++++++++++++++
- name: TASK - install / configure session-recording | COCKPIT SESSION RECORDING
  import_tasks: redhat8_session-recording.yml
  tags:
    - config_redhat8_session-recording
    - RedHat8
    - global_redhat_security_features
#-------------------------------------------
- debug: msg="++++++++++++++++++++++++ TASK - verify / configure systemd unit"++++++++++++++++++++++++
- name: TASK - configure systemd unit
  import_tasks: redhat8_systemd_config.yml
  tags:
    - config_redhat8_systemd
    - RedHat8
    - global_redhat_security_features
...