---
# File redhat7_setup.yml for the task that config ONLY CentOs "7" servers

#-------------------------------------------
- name: obtain the OS version
  shell: cat /etc/centos-release
  register: result_os_version
- name: rdisplay the O/S version
  debug: msg= "{{ result_os_version }}"
#-------------------------------------------
...