---
# file for roles/tasks/session-recording.yml
- name: Install the cockpit-session-recording package
  yum:
    name:
      - tlog
      - cockpit-session-recording
    state: present
    update_cache: true
  become: true
  notify:
    - enable cockpit.socket
    - restart sssd
  register: yum_cockpit_session_recording_output
- debug:
    var: yum_cockpit_session_recording_output
#----------------------------------
...