---
# handlers file for roles/global_redhat_security_features

# handlers for fapolicyd.yml
- name: enable fapolicyd
  service: name=fapolicyd enabled=yes
- name: restart fapolicyd
  service: name=fapolicyd state=restarted

# handlers for session-recording.yml
- name: enable cockpit.socket
  service: name=cockpit.socket enabled=yes
- name: restart sssd
  service: name=sssd state=restarted