---
# handlers file for roles/report_global_redhat_security_features

# handlers for fapolicyd.yml
- name: enable fapolicyd
  service: name=fapolicyd enabled=yes
- name: restart fapolicyd
  service: name=fapolicyd state=restarted

# handlers for session-recording.yml
- name: enable cockpit_session_recording
  service: name=cockpit_session_recording enabled=yes
- name: restart cockpit_session_recording
  service: name=cockpit_session_recording state=restarted